Convert demo to standard GeoTrellis deployment framework
geotrellis/geotrellis-pointcloud-demo pull request #12
Opened 2017-09-21 20:55 UTC by tnation14

# Overview
This PR adds a pipeline to build/deploy API Server and Nginx Containers to AWS. Also, add Terraform resources for an AWS ECS Service, using CloudFront as a CDN.

## Notable changes
- Update Docker/Compose
- Remove `azavea.*` Ansible scripts from the repository (they're downloaded with `ansible-galaxy` at the beginning of every provisioning run)
- Add a dockerized deployment environment
- Add containers to serve static files and run the API server
- Replace `webpack-dev-server` with `nginx` as the default way to serve static files in development
- Add Terraform configuration for an AWS ECS service using our `terraform-aws-ecs-web-service` module
- Add STRTA to necessary for build/deployment pipeline
- Configure TravisCI for deployment

## Notes
- The JavaScript for main site is broken, and won't pass tests. Scala also throws compilation errors when compiling the `ingest` JAR, but not the `server` one. As a workaround, I've skipped JS tests, and only build the `server` JAR (which I think is the only one we need anyway).

- I ran into some Scala dependency resolution issues, and added a Sonatype repo to get everything to work. I'm not sure if this is WAI, or if the LocationTech repo needs to be updated.

- Although I wanted to keep using webpack-dev-server running in development, making the frontend work with both dev and production URLs proved to be tricky. I opted towards just using Nginx instead.

- The backend service displays a small weighted Overlay, but I'm unsure if it should be larger than it is. @lossyrob can you confirm that the backend is functioning?

# Testing
- see https://pointcloud.geotrellis.io
- See Travis CI output
- in development, provision a VM, and run `scripts/server`. Nginx should be available at http://localhost:8000.
    - I also hit http://localhost:8000/ping to be sure that nginx is rewriting URLs properly.

Fixes #11

2017-09-22 16:47 UTC, hectcastro approved these changes
Looks good. I was able to get things working locally, and the app appears to be somewhat functional in AWS. I did see a bunch of Webpack bundle warnings, which could be leading to broken behavior, but I'm not sure what things look like when it is working either.

2017-09-22 16:47 UTC, hectcastro commented on Vagrantfile
>    config.vm.synced_folder "data", "/home/vagrant/data"
Getting a failure on fresh checkout because `data` is missing. May need to create this in `setup`.

2017-09-22 16:47 UTC, hectcastro commented on src/app-backend/.dockerignore
> +!server/target/scala-2.11/pointcloud-server-assembly-0.1.0-SNAPSHOT.jar
Might be good to adjust this so that it catches assembly JARs after 0.1.0.

2017-09-22 16:47 UTC, hectcastro commented on src/app-backend/Dockerfile
> +COPY server/target/scala-2.11/pointcloud-server-assembly-0.1.0-SNAPSHOT.jar /srv/
Same here with reference to 0.1.0. Might be able to alter the `sbt` configuration so that the version isn't in the file name. Could also do a `mv` that renames it after it is built.

2017-10-11 01:16 UTC, lossyrob commented
Having trouble running this. I ran `scripts/setup.sh`, and then inside the vm `scripts/cibuild.sh` and `scripts/server.sh`. Navigating to localhost:8000 I'm getting:

<img width="859" alt="screen shot 2017-10-10 at 9 15 17 pm" src="https://user-images.githubusercontent.com/2320142/31417841-2be73246-ae00-11e7-8ba3-ff53f1b251ab.png">

Am I skipping a step?

2017-10-11 16:53 UTC, tnation14 commented
I don't think so; I just rebuilt my VM from scratch and was able to run `scripts/setup.sh` and `scripts/server.sh`, then hit localhost:8000. `scripts/setup.sh` runs `scripts/update.sh`; did any part of that script fail? It seems like the JavaScript bundle didn't build properly.

2017-10-17 19:27 UTC, tnation14 commented
@lossyrob Just wanted to circle back and see if you were able to fix your Dev environment issues. Did you have any success after running `scripts/update` again?

2017-10-17 19:41 UTC, lossyrob commented
Thanks for looping back - I didn't have a watch on on this repo until today, and so didn't see your comment. The Azavea GeoTrellis team is putting this on their next sprint - and if someone else doesn't pick it up I'll be able to take a look when I get from State of the Map travels next week.

2017-11-16 21:53 UTC, echeipesh commented
Encountered the same error as @lossyrob but after `vagrant destroy` `vagrant up` `./scripts/setup.sh` and `./scripts/update.sh` inside the container I was able to see the `index.html` but the page is unresponsive and the service is is throwing `500` which I have not investigated yet.

I had to bump the dependencies for `geotrellis-pointcloud` to newly published branch. I assume you guys must have been doing `publish-local` from feature branch in order to have `1.1.0-PC-SNAPSHOT` artifact available? I also assume the demo was working fine with that so I'm possibly looking at some kind of regression with the update to published `geotrellis-pointcloud`.

2017-11-20 17:52 UTC, tnation14 commented
> I was able to see the index.html but the page is unresponsive and the service is is throwing 500 which I have not investigated yet.

I ran into this locally, and it was because the API server was silently failing to start with OOM errors. I had some success by setting `JAVA_OPTS="-Xmx512M"`. Doing 

```bash
$ docker-compose run --rm pc-api-server
```
Will start the API server only, so you can see if that is indeed the issue without seeing any other output from Nginx.
 
> II had to bump the dependencies for geotrellis-pointcloud to newly published branch. I assume you guys must have been doing publish-local from feature branch in order to have 1.1.0-PC-SNAPSHOT artifact available?

Do you mean did I update the `geotrellis-pointcloud` version? I didn't, this demo is still using `0.1.0-PC-SNAPSHOT`. I just corrected a typo in the JAR name.

2019-04-24 01:10 UTC, pomadchin requested changes
This is a non working demo, and can't be merged since it doesn't contain pretty important changes from this PR #8, I will try to rebase this PR on top of it.

2019-04-24 02:14 UTC, pomadchin commented
It is a part of https://github.com/geotrellis/geotrellis-pointcloud-demo/pull/16 now

2019-04-24 02:14 UTC, closed without merging